#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1557964462                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : assets/artbox-presskit.zip                                     # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Home for your family's arts & crafts.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : rakTech LLC                              
your_link                                 : https://raktech.app                  
your_city                                 : the USA                                
email_address                             : support@raktech.app
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : thatvirtualboy
github_username                           : thatvirtualboy
youtube_username                          : thatvirtualboy
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Organize Every Masterpiece
    description                           : Save photos of each artwork with notes, dates, and keywords - beautifully organized.
    fontawesome_icon_name                 : folder-open
    
  - title                                 : Quick Capture on iPhone & iPad
    description                           : Add new pieces in seconds from your camera or library — perfect for school pickups and fridge clean‑offs.
    fontawesome_icon_name                 : camera

  - title                                 : Private iCloud Sync
    description                           : Your family’s gallery stays safe and in sync across devices using your iCloud account.
    fontawesome_icon_name                 : cloud

  - title                                 : Share with Family
    description                           : Privately share a child’s gallery with grandparents, co‑parents, or anyone you choose via iCloud sharing.
    fontawesome_icon_name                 : user-friends

  - title                                 : Turn Art into Photo Books
    description                           : Create beautiful, real‑world photo books of your artists’ work straight from Artbox.
    fontawesome_icon_name                 : book-open
  
  - title                                 : Smart Search & Filters
    description                           : Instantly find pieces by artist, favorites, or keywords.
    fontawesome_icon_name                 : search

  - title                                 : Works Offline
    description                           : Capture and organize anywhere—your changes sync to iCloud when you’re back online.
    fontawesome_icon_name                 : cloud-download-alt

  - title                                 : Export & Print
    description                           : Export your saved projects at any time for printing, sharing, and school portfolios.
    fontawesome_icon_name                 : file-pdf

  - title                                 : No Shady Business
    description                           : Artbox is built for families. No, gimmicks, or data selling.
    fontawesome_icon_name                 : shield-alt

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black1                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#7fc6f0"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#7fc6f0"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
